# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a54fc5f8717a23e0fe0eafcac6a32f00071d3235d819896f360c364a8d411360194b1a832212b02b3334ee5cd8e711d8821f3ba3616c9f7cd59f481bf7b0bbc2

test:
  secret_key_base: c02a67eab1998fa587b958521bf8ef5fb06f742d2353ac63c819b98f8c20233d2c728c1601c9546ce488b35959e510af6b3488e39c58cd523d58ff35047c41e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
